http.poolNames = aliyun,gaotie,amap,WebParser,visualops,12306,shuqi,feishumcp
##aliyun mcp模型服务配置：在代码中引用服务的名称为aliyun
# 服务连接池参数
aliyun.http.maxTotal = 200
aliyun.http.defaultMaxPerRoute = 200
# aliyun模型服务地址
aliyun.http.hosts=https://dashscope.aliyuncs.com
#基于apiKeyId认证配置（主要用于各种大模型服务对接认证）
aliyun.http.apiKeyId = sk-469f01dbb572db4fb2f4
# sse端点：高德地图用户key申请地址，https://console.amap.com/dev/key/app
aliyun.http.extendConfigs.sseendpoint = /api/v1/mcps/amap-maps/sse?key=793b8ba3f2fa74cba764a8

##WebParser mcp模型服务配置：在代码中引用服务的名称为WebParser
# 服务连接池参数
WebParser.http.maxTotal = 200
WebParser.http.defaultMaxPerRoute = 200
# WebParser模型服务地址
WebParser.http.hosts=https://dashscope.aliyuncs.com
#基于apiKeyId认证配置（主要用于各种大模型服务对接认证）
WebParser.http.apiKeyId = sk-469f01dbb5724efb2f4
# sse端点：高德地图用户key申请地址，https://console.amap.com/dev/key/app
WebParser.http.extendConfigs.sseendpoint = /api/v1/mcps/WebParser/sse


##gaode mcp模型服务配置：在代码中引用服务的名称为amap
# 服务连接池参数
amap.http.maxTotal = 200
amap.http.defaultMaxPerRoute = 200
# amap模型服务地址
amap.http.hosts=https://mcp.amap.com
#基于apiKeyId认证配置（主要用于各种大模型服务对接认证）
#amap.http.apiKeyId = sk-469f01dbbd6d6db4fb2f4
# sse端点：高德地图用户key申请地址，https://console.amap.com/dev/key/app
amap.http.extendConfigs.sseendpoint = /sse?key=793b8ba

##gaotie mcp模型服务配置：在代码中引用服务的名称为gaotie
# 服务连接池参数
gaotie.http.maxTotal = 200
gaotie.http.defaultMaxPerRoute = 200
 gaotie模型服务地址
gaotie.http.hosts=127.0.0.1:8000
gaotie.http.extendConfigs.sseendpoint = /sse

##12306 mcp模型服务配置：在代码中引用服务的名称为12306
# 服务连接池参数
12306.http.maxTotal = 200
12306.http.defaultMaxPerRoute = 200
# 12306服务地址
12306.http.hosts=https://dashscope.aliyuncs.com
12306.http.apiKeyId = sk-469f01dbb5724e6db4fb2f4
12306.http.extendConfigs.sseendpoint = /api/v1/mcps/china-railway/sse

##shuqi mcp模型服务配置：在代码中引用服务的名称为shuqi
# 服务连接池参数
shuqi.http.maxTotal = 200
shuqi.http.defaultMaxPerRoute = 200
# shuqi服务地址
shuqi.http.hosts=https://dashscope.aliyuncs.com
shuqi.http.apiKeyId = sk-469f01dbb576d6db4fb2f4
shuqi.http.extendConfigs.streamableendpoint = /api/v1/mcps/market-cmapi00072981/mcp
#shuqi.http.httpResponseInterceptors=org.frameworkset.spi.ai.HttpResponseInterceptorDemo

##visualops mcp模型服务配置：在代码中引用服务的名称为visualops
# 服务连接池参数
visualops.http.maxTotal = 200
visualops.http.defaultMaxPerRoute = 200
# visualops服务地址
#visualops.http.hosts=127.0.0.1:8080
visualops.http.hosts=10.13.6.4:8128
visualops.http.apiKeyId = 17689048891Odh23DX4NT
#visualops.http.extendConfigs.sseendpoint = /mcp/sse.api
visualops.http.extendConfigs.streamableendpoint = /mcp/streamable.api
#visualops.http.httpResponseInterceptors=org.frameworkset.spi.ai.HttpResponseInterceptorDemo

##feishumcp mcp模型服务配置：在代码中引用服务的名称为feishumcp
# 服务连接池参数
feishumcp.http.maxTotal = 200
feishumcp.http.defaultMaxPerRoute = 200
# feishumcp服务地址
feishumcp.http.hosts=https://mcp.feishu.cn
feishumcp.http.extendConfigs.streamableendpoint = /mcp
 
 